-- Migration: Wallet System
-- Electronic wallet for customers — charged via codes from super admin, used for payments

-- ═══════════════════════════════════════════════════════════════
-- 1. wallet_transactions — ledger (credit/debit rows)
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.wallet_transactions (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id  UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  amount       NUMERIC(10,2) NOT NULL,
  type         TEXT NOT NULL CHECK (type IN ('topup', 'payment', 'refund')),
  description  TEXT,
  reference_id UUID,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.wallet_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "customer sees own wallet transactions"
  ON public.wallet_transactions FOR SELECT
  USING (auth.uid() = customer_id);

CREATE INDEX idx_wallet_tx_customer ON public.wallet_transactions(customer_id, created_at DESC);

-- ═══════════════════════════════════════════════════════════════
-- 2. wallet_codes — top-up codes generated by super admin
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.wallet_codes (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code         TEXT NOT NULL UNIQUE,
  amount       NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  created_by   UUID REFERENCES auth.users(id),
  redeemed_by  UUID REFERENCES auth.users(id),
  redeemed_at  TIMESTAMPTZ,
  is_used      BOOLEAN DEFAULT FALSE,
  expires_at   TIMESTAMPTZ,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.wallet_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "customer sees own redeemed codes"
  ON public.wallet_codes FOR SELECT
  USING (auth.uid() = redeemed_by);

CREATE POLICY "admin manages wallet codes"
  ON public.wallet_codes FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role IN ('super_admin', 'admin', 'regional_manager')
    )
  );

-- ═══════════════════════════════════════════════════════════════
-- 3. get_wallet_balance — returns sum of all transactions
-- ═══════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.get_wallet_balance(p_customer_id UUID)
RETURNS NUMERIC LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_balance NUMERIC;
BEGIN
  SELECT COALESCE(SUM(amount), 0) INTO v_balance
  FROM public.wallet_transactions
  WHERE customer_id = p_customer_id;
  RETURN v_balance;
END;
$$;

-- ═══════════════════════════════════════════════════════════════
-- 4. redeem_wallet_code — validate code, credit wallet
-- ═══════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.redeem_wallet_code(p_code TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_code_row   RECORD;
  v_customer_id UUID;
BEGIN
  v_customer_id := auth.uid();
  IF v_customer_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'يجب تسجيل الدخول أولاً');
  END IF;

  SELECT * INTO v_code_row
  FROM public.wallet_codes
  WHERE code = UPPER(TRIM(p_code))
  FOR UPDATE;

  IF v_code_row IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'الكود غير صحيح');
  END IF;

  IF v_code_row.is_used THEN
    RETURN jsonb_build_object('success', false, 'error', 'هذا الكود مُستخدم بالفعل');
  END IF;

  IF v_code_row.expires_at IS NOT NULL AND v_code_row.expires_at < NOW() THEN
    RETURN jsonb_build_object('success', false, 'error', 'هذا الكود منتهي الصلاحية');
  END IF;

  UPDATE public.wallet_codes
  SET is_used = TRUE, redeemed_by = v_customer_id, redeemed_at = NOW()
  WHERE id = v_code_row.id;

  INSERT INTO public.wallet_transactions (customer_id, amount, type, description, reference_id)
  VALUES (v_customer_id, v_code_row.amount, 'topup',
          'شحن المحفظة — كود #' || SUBSTRING(v_code_row.code, 1, 8),
          v_code_row.id);

  RETURN jsonb_build_object(
    'success', true,
    'amount',  v_code_row.amount,
    'message', 'تم شحن المحفظة بنجاح'
  );
END;
$$;

-- ═══════════════════════════════════════════════════════════════
-- 5. deduct_wallet_balance — validate balance, debit wallet
-- ═══════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.deduct_wallet_balance(
  p_customer_id UUID,
  p_amount      NUMERIC,
  p_order_id    UUID DEFAULT NULL,
  p_description TEXT DEFAULT 'دفع طلب من المحفظة'
)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_balance NUMERIC;
BEGIN
  SELECT COALESCE(SUM(amount), 0) INTO v_balance
  FROM public.wallet_transactions
  WHERE customer_id = p_customer_id;

  IF v_balance < p_amount THEN
    RETURN jsonb_build_object('success', false, 'error', 'رصيد المحفظة غير كافٍ',
                               'balance', v_balance, 'required', p_amount);
  END IF;

  INSERT INTO public.wallet_transactions (customer_id, amount, type, description, reference_id)
  VALUES (p_customer_id, -p_amount, 'payment', p_description, p_order_id);

  RETURN jsonb_build_object(
    'success',   true,
    'remaining', v_balance - p_amount
  );
END;
$$;

COMMENT ON FUNCTION public.get_wallet_balance(UUID) IS 'إرجاع رصيد المحفظة';
COMMENT ON FUNCTION public.redeem_wallet_code(TEXT) IS 'استرداد كود شحن المحفظة';
COMMENT ON FUNCTION public.deduct_wallet_balance(UUID, NUMERIC, UUID, TEXT) IS 'خصم من رصيد المحفظة عند الدفع';
